name: Descargar por Fecha

on:
  workflow_dispatch:
    inputs:
      fecha:
        description: 'Fecha a descargar (YYYY-MM-DD)'
        required: true
        type: string
      correo:
        description: 'Correo destinatario'
        required: true
        type: string

jobs:
  descargar-todo:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - name: Descargar 3 archivos y enviar en 1 correo
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          DEST_EMAIL: ${{ inputs.correo }}
          TARGET_DATE: ${{ inputs.fecha }}
        run: python descargar_fecha.py
